# Tomcat
server:
  port: 9700
#多环境配置
spring:
  application:
    # 应用名称
    name: lianxi-redis-lock
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 500
        max-idle: 1000
        min-idle: 4