# Tomcat
server:
  port: 9000
#多环境配置
spring:
  application:
    # 应用名称
    name: lianxi-zookeeper
  profiles:
    active: dev

zookeeper:
  address: 192.168.56.101:2181,192.168.56.103:2181,192.168.56.104:2181
  timeout: 4000
