# Tomcat
server:
  port: 9801
spring:
  application:
    name: lianxi-biz1
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    host: 192.168.56.101
    port: 5432
    database: postgres
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
    listener:
      enable: true
  cloud:
    nacos:
      username: nacos
      password: nacos123456
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - optional:nacos:application-dev.yml
      - optional:nacos:lianxi-biz-dev.yml

# seata配置
seata:
  enabled: true # spring 自动装配
  enable-auto-data-source-proxy: true # 开启数据源自动代理
  tx-service-group: my-tx-group #事务组名称 必须一定和你服务端配置的一样 必须 必须 必须
  application-id: ${spring.application.name}
  service:
    vgroup-mapping:
      default-tx-group: GZ  #事务组内容 须一定和你服务端配置的一样
      # 配置中心按照这个要求配置和服务端类似
  config:
    type: nacos
    nacos:
      group: SEATA_GROUP
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos123456
      # 注册中心按照这个要求配置和服务端类似
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      username: nacos
      password: nacos123456
      cluster: GZ
      group: SEATA_GROUP



