# Tomcat
server:
  port: 9300
#多环境配置
spring:
  application:
    # 应用名称
    name: lianxi-file
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 500
        max-idle: 1000
        min-idle: 4
  servlet:
    multipart:
      max-file-size: 1024MB
  # Spring Boot Admin 监控服务器端地址
  boot:
    admin:
      client:
        url: http://localhost:9400

  data:
    mongodb:
      host: 192.168.56.101
      port: 27017
      database: test
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        master:
          driver-class-name: org.postgresql.Driver
          password: 123456
          url: jdbc:postgresql://192.168.56.101:5432/postgres
          username: postgres
        slave_1:
          url: jdbc:mysql://192.168.56.101:3306/file_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
        slave_2:
          driver-class-name: org.postgresql.Driver
          password: 123456
          url: jdbc:postgresql://192.168.56.101:5432/postgres
          username: postgres
      # 自定义负载均衡策略。slave组下有；多个个数据源，当用户使用 slave 切换数据源时会使用负载均衡算法。系统自带了两个负载均衡算法 LoadBalanceDynamicDataSourceStrategy 轮询,是默认的。 RandomDynamicDataSourceStrategy 随机的。
      strategy: com.baomidou.dynamic.datasource.strategy.LoadBalanceDynamicDataSourceStrategy
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    password: 123456
#    url: jdbc:postgresql://192.168.56.101:5432/postgres
#    username: postgres
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    logfile:
      external-file: D:\\workspaces\\lianxi\\logs\\lianxi-file\\info.log
logging:
  config: classpath:logback.xml

##ftp配置
ftp:
  #FTP地址
  host: 192.168.56.101
  #FTP端口
  port: 21
  #FTP用户名
  userName: ftptest
  #FTP密码
  passWord: 12345678
  #目录
  workDirectory: /upload
  #FTP根目录
  root: /
  #编码
  encoding: utf-8
  #最多连接数
  maxTotal: 100
  minIdle: 3
  maxIdle: 5
  maxWaitMillis: 30000000

# 本地文件上传
file:
  domain: http://127.0.0.1:9300
  path: D:/zxicet/uploadPath
  prefix: /statics

# FastDFS配置
fdfs:
  domain: http://192.168.56.104:8888
  soTimeout: 3000
  connectTimeout: 2000
  trackerList: 192.168.56.104:22122

# Minio配置
minio:
  url: http://192.168.56.104:9000
  accessKey: admin
  secretKey: admin123
  bucketName: test
  allow-file-type: jpg,png,jpeg,zip,rar,doc,docx,xls,xlsx,img,iso
  # 分片上传有效期: 秒
  chunk-upload-expiry-second: 86400


mybatis:
  configuration:
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mybatis/*.xml
  type-aliases-package: com.lianxi.file.enity