# Tomcat
server:
  port: 9500
#多环境配置
spring:
  application:
    # 应用名称
    name: lianxi-xxljob

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://192.168.56.101:9080/xxl-job-admin
    ### xxl-job, access token
    accessToken: default_token
    ### xxl-job executor appname
    executor:
      appname: ${spring.application.name}
      ### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address:
      ### xxl-job executor server-info
      ip:
      port: 9999
      ### xxl-job executor log-path
      logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job executor log-retention-days
      logretentiondays: 30